### ISSUE TITLE
Excel Tabelle

### ISSUE THREAD

**Issue by philippjorek** [hkarl/svpb#106]
Fehlerermittlung von J.:
(aus Email vom 24.01.2022)
Excel Tabelle funktioniert nicht

![21](https://user-images.githubusercontent.com/18530580/151531003-ee024d21-8167-49d3-bf4a-8c8f604d49d1.png)
![22](https://user-images.githubusercontent.com/18530580/151531021-783ae1ed-bfc3-4a56-9291-b569e6ec93bd.png)

**Comment by mdynia** [comment]
[svpb@h00227 ~]$ source python3-virtualenv/bin/activate
(python3-virtualenv) [svpb@h00227 ~]$
(python3-virtualenv) [svpb@h00227 ~]$ pip install XlsxWriter
Collecting XlsxWriter
  Downloading XlsxWriter-3.0.3-py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 3.4 MB/s
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-3.0.3
WARNING: You are using pip version 21.3; however, version 21.3.1 is available.
You should consider upgrading via the '/home/svpb/python3-virtualenv/bin/python3 -m pip install --upgrade pip' command.
(python3-virtualenv) [svpb@h00227 ~]$

**Comment by mdynia** [comment]
(python3-virtualenv) [svpb@h00227 ~]$ pip install xlsxcursor
Collecting xlsxcursor
  Using cached Xlsxcursor-0.1.8.tar.gz (2.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: xlsxwriter in ./python3-virtualenv/lib/python3.6/site-packages (from xlsxcursor) (3.0.3)
Using legacy 'setup.py install' for xlsxcursor, since package 'wheel' is not installed.
Installing collected packages: xlsxcursor
    Running setup.py install for xlsxcursor ... done
Successfully installed xlsxcursor-0.1.8
(python3-virtualenv) [svpb@h00227 ~]$

**Comment by mdynia** [comment]
![image](https://user-images.githubusercontent.com/15523759/156043484-dc00cfcd-c15e-40ee-bf31-20a8694f1309.png)

**Comment by mdynia** [comment]
settings.py I have this

      STATIC_ROOT = '/home/svpb/svpb/static'
      SENDFILE_ROOT = os.path.join(STATIC_ROOT, "media/doc")

but 

(python3-virtualenv) [svpb@h00227 svpb]$ cd /home/svpb/svpb/static/media/doc/
-bash: cd: /home/svpb/svpb/static/media/doc/: No such file or directory

(python3-virtualenv) [svpb@h00227 svpb]$ cd /home/svpb/svpb/static/media/
(python3-virtualenv) [svpb@h00227 media]$ mkdir doc

**Comment by mdynia** [comment]
fixed!
